import React, { useState } from 'react';
import { History, Sparkles, Search, Trash2, Filter, ArrowUpDown } from 'lucide-react';
import Button from '../components/Button';

export default function HistoryPage({ historyList, onClearHistory, onNavigateToPredict }) {
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState('All');

  // Filter history items
  const filteredItems = historyList.filter((item) => {
    const matchesSearch =
      item.date.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.price.toString().includes(searchTerm) ||
      item.predictedBoxes.toString().includes(searchTerm);

    const matchesStatus = filterStatus === 'All' || item.status === filterStatus;
    return matchesSearch && matchesStatus;
  });

  return (
    <div className="fade-in">
      <div className="card">
        <div className="card-header" style={{ flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <h3 className="card-title">
              <History size={20} color="var(--color-accent)" />
              <span>Prediction Audit Trail</span>
            </h3>
            <p className="card-subtitle">
              Record of forecasted chocolate paan box sales generated by the machine learning model.
            </p>
          </div>

          {/* Search & Filter Tools */}
          {historyList.length > 0 && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem', flexWrap: 'wrap' }}>
              <div className="input-control-wrap" style={{ width: '200px' }}>
                <span className="input-prefix"><Search size={15} /></span>
                <input
                  type="text"
                  placeholder="Search date or price..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="text-input has-prefix"
                  style={{ padding: '0.45rem 0.8rem 0.45rem 2rem', fontSize: '0.85rem' }}
                />
              </div>

              <select
                value={filterStatus}
                onChange={(e) => setFilterStatus(e.target.value)}
                className="text-input"
                style={{ padding: '0.45rem 0.8rem', fontSize: '0.85rem', width: 'auto' }}
              >
                <option value="All">All Tiers</option>
                <option value="High">High Demand</option>
                <option value="Medium">Medium Demand</option>
                <option value="Low">Low Demand</option>
              </select>

              <button
                className="btn btn-secondary"
                style={{ padding: '0.45rem 0.85rem', fontSize: '0.82rem', color: '#B32D20' }}
                onClick={onClearHistory}
                title="Clear all saved history"
              >
                <Trash2 size={15} />
                <span>Clear</span>
              </button>
            </div>
          )}
        </div>

        {/* Table or Empty State */}
        {filteredItems.length === 0 ? (
          <div className="empty-state-box">
            <div className="empty-icon-wrap">
              <History size={32} />
            </div>
            <h3>No predictions found</h3>
            <p>
              {historyList.length === 0
                ? 'Make your first sales prediction to see it logged here with business conditions.'
                : 'No historical records matched your search query or tier filter.'}
            </p>
            <Button
              variant="accent"
              icon={Sparkles}
              onClick={onNavigateToPredict}
            >
              Make Prediction
            </Button>
          </div>
        ) : (
          <div className="table-responsive">
            <table className="modern-table">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Temperature</th>
                  <th>Price</th>
                  <th>Discount</th>
                  <th>Marketing Budget</th>
                  <th>Predicted Boxes</th>
                  <th>Demand Status</th>
                </tr>
              </thead>
              <tbody>
                {filteredItems.map((item) => (
                  <tr key={item.id}>
                    <td style={{ fontWeight: 600 }}>{item.date}</td>
                    <td>{item.temperature}°C</td>
                    <td style={{ fontWeight: 600 }}>₹{item.price}</td>
                    <td>{item.discountPercentage}%</td>
                    <td>₹{item.marketingBudget.toLocaleString()}</td>
                    <td style={{ fontWeight: 800, fontSize: '1.05rem', color: 'var(--color-primary)' }}>
                      {item.predictedBoxes.toLocaleString()}
                    </td>
                    <td>
                      <span
                        className={`demand-badge ${
                          item.status === 'High'
                            ? 'badge-high'
                            : item.status === 'Low'
                            ? 'badge-low'
                            : 'badge-medium'
                        }`}
                        style={{ margin: 0, padding: '0.25rem 0.75rem', fontSize: '0.8rem' }}
                      >
                        {item.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
